// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/re-partners-challenge-backend/internal/domain/service/package"
	"github.com/re-partners-challenge-backend/internal/handler/http/health"
	"github.com/re-partners-challenge-backend/internal/handler/http/httppackage"
	"github.com/re-partners-challenge-backend/internal/infra/config"
	"github.com/re-partners-challenge-backend/internal/infra/httprouter"
	"github.com/re-partners-challenge-backend/internal/infra/httpserver"
	"github.com/re-partners-challenge-backend/internal/infra/log"
	"github.com/re-partners-challenge-backend/internal/infra/middleware"
	"github.com/re-partners-challenge-backend/internal/persistence/database"
	"github.com/re-partners-challenge-backend/internal/persistence/packagepersistence"
	"github.com/re-partners-challenge-backend/internal/usecase/packageusecase"
)

// Injectors from wire.go:

func Build() (Application, func(), error) {
	zapLogger, err := log.ProvideLogger()
	if err != nil {
		return Application{}, nil, err
	}
	configReader := config.ProvideConfigReader(zapLogger)
	configConfig, err := config.ProvideConfig(configReader)
	if err != nil {
		return Application{}, nil, err
	}
	cors := httpserver.ProvideCORSMiddleware(configConfig)
	healthCheckHandler := health.ProvideHealthCheckHandler()
	router := health.ProvideRouter(healthCheckHandler)
	fakeDatabase := database.ProvideDatabase(zapLogger)
	repositoryPackage := packagepersistence.ProvidePackageRepository(zapLogger, fakeDatabase)
	servicePackage := packageservice.ProvidePackageService(zapLogger, repositoryPackage)
	usecasePackage := packageusecase.ProvidePackageUseCase(zapLogger, servicePackage)
	getPackagesHandler := httppackage.ProvideGetPackagesHandler(zapLogger, usecasePackage)
	updatePackagesHandler := httppackage.ProvideUpdatePackagesHandler(zapLogger, usecasePackage)
	httppackageRouter := httppackage.ProvideRouter(getPackagesHandler, updatePackagesHandler)
	routes := httpserver.Routes{
		HealthCheckRouter: router,
		PackageRouter:     httppackageRouter,
	}
	middlewareMiddleware := middleware.ProvideErrorHandlerMiddleware(zapLogger)
	v := httpserver.ProvideCoreMiddlewares(zapLogger, middlewareMiddleware)
	bunrouterRouter, err := httprouter.ProvideRouter(zapLogger, configConfig, routes, v...)
	if err != nil {
		return Application{}, nil, err
	}
	handler := httpserver.ProvideHandler(cors, bunrouterRouter)
	serverOption := &httpserver.ServerOption{
		Config:  configConfig,
		Handler: handler,
		Logger:  zapLogger,
	}
	server := httpserver.ProvideHTTPServer(serverOption)
	application := ProvideApplication(configConfig, server)
	return application, func() {
	}, nil
}
