// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/re-partners-challenge-backend/internal/handler/http/health"
	"github.com/re-partners-challenge-backend/internal/infra/config"
	"github.com/re-partners-challenge-backend/internal/infra/httprouter"
	"github.com/re-partners-challenge-backend/internal/infra/httpserver"
	"github.com/re-partners-challenge-backend/internal/infra/log"
)

// Injectors from wire.go:

func Build() (Application, func(), error) {
	logger, err := log.ProvideZapLogger()
	if err != nil {
		return Application{}, nil, err
	}
	configReader := config.ProvideConfigReader(logger)
	configConfig, err := config.ProvideConfig(configReader)
	if err != nil {
		return Application{}, nil, err
	}
	healthCheckHandler := health.ProvideHealthCheckHandler()
	router := health.ProvideRouter(healthCheckHandler)
	routes := httpserver.Routes{
		HealthCheckRouter: router,
	}
	handler, err := httprouter.ProvideRouter(logger, configConfig, routes)
	if err != nil {
		return Application{}, nil, err
	}
	serverOption := &httpserver.ServerOption{
		Config:  configConfig,
		Handler: handler,
		Logger:  logger,
	}
	server := httpserver.ProvideHTTPServer(serverOption)
	application := ProvideApplication(configConfig, server)
	return application, func() {
	}, nil
}
